site_name: Linux 银河漫游指南
repo_url: https://github.com/linuxhitchhiker/THGLG
edit_uri: edit/main/docs/
copyright: "© 2022 Linux 银河漫游指南贡献者，在 CC-BY-SA 4.0 下提供。"

nav:
  - 主页:
      - 欢迎: index.md
      - 简介: intro.md
  - 入门指南:
      - 序言:
          - 切换到 Linux: entry/prologue/switch-to-linux.md
          - Linux 发行版: entry/prologue/choose-distro.md
          - 桌面环境简介: entry/prologue/desktop-environment.md
      - 安装系统:
          - 安装前准备: entry/installation/pre-install.md
          - 校验文件: entry/installation/verify.md
          - 虚拟机: entry/installation/virtual-machine.md
          - Fedora 安装指南: entry/installation/fedora.md
          - Fedora Silverblue 安装指南: entry/installation/fedora-silverblue.md
          - openSUSE 安装指南: entry/installation/opensuse.md
        #- 使用桌面环境:
        #- 安装软件（图形化界面）: entry/desktop/apps-gui.md
  - 进阶教程:
      - 使用命令行:
          - advanced/shell/index.md
          - advanced/shell/base1.md
          - advanced/shell/base2.md
          - advanced/shell/base3.md
          - advanced/shell/base4.md
          - advanced/shell/base5.md
      - 配置系统:
          - advanced/system-admin/index.md
          - advanced/system-admin/update-sys.md
          - advanced/system-admin/package-manager.md
          - advanced/system-admin/setup-proxy.md
          - advanced/system-admin/nvidia-driver.md
          - advanced/system-admin/firewall.md
          - advanced/system-admin/systemctl.md
      - 再次入门:
          - 概述: advanced/re-entry/index.md
          - 选择发行版: advanced/re-entry/distro.md
          - 软件源与镜像源: advanced/re-entry/repo-and-mirror.md
          - 硬盘与文件系统: advanced/re-entry/disk-and-fs.md
          - 扩展阅读: advanced/re-entry/extend.md
  - 高级教程:
      - 概述: poweruser/index.md
  - 解决方案:
      - 系统美化:
          - 概述: solution/eyecandy/index.md
          - KDE 美化: solution/eyecandy/eyecandy-kde.md
          - Xfce4 美化: solution/eyecandy/eyecandy-xfce4.md
      - 软件:
          - 概述: solution/software/index.md
          - 浏览器: solution/software/browser.md
          - 即时通讯: solution/software/instant-messaging.md
          - 文档办公: solution/software/office-and-email.md
          - 多媒体相关: solution/software/multimedia-editing.md
          - 下载器: solution/software/download-manager.md
          - 游戏: solution/software/linux-game.md
          - Appimage: solution/software/appimage-base.md
          - Flatpak: solution/software/flatpak-get-start.md
      - 系统配置:
          - 概述: solution/config/index.md
          - HiDPI: solution/config/hidpi.md
          - 双系统: solution/config/dual-boot.md
      - 跨系统兼容:
          - 概述: solution/compatibility/about.md
          #- Wine: solution/compatibility/wine.md
          #- Toolbx: solution/compatibility/toolbx.md
          #- Docker: solution/compatibility/docker.md
          #- Distrobox: solution/compatibility/distrobox.md
          - 搭建虚拟机: solution/compatibility/virtual-machine.md
  - 寻求帮助:
      - 常见问题: help/faq.md
      - 如何提问: help/howto-ask-for-help.md
  - 关于:
      - 简介: about/index.md
      - 许可协议: about/license/index.md
      - 贡献指南:
          - 快速指南: about/contributing/index.md
          #- 简约 lite 版: about/contributing/about.md
          - 慢速开始 1: about/contributing/base-01.md
          - 慢速开始 2: about/contributing/base-02.md

theme:
  name: material
  language: zh
  custom_dir: overrides
  locale: zh_CN
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

plugins:
  - git-revision-date-localized:
      locale: en
      type: iso_datetime
      enable_creation_date: true
      exclude:
        - index.md
        - "intro.md"
        - about/*
  - search:
      lang: zh

markdown_extensions:
  - def_list
  - abbr
  - md_in_html
  - footnotes
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
# extra_css:
#   - assets/stylesheets/extra.css
